apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storge: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  presistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdNme: mysql
    fsType: ext4
